### ISSUE TITLE
Allow Sorting When Not Filterable

### ISSUE THREAD

**Issue by rslsystems** [ukfast/laravel-sieve#10]
### What is the feature?

At present, an attempt to sort will not work unless the field in question is also filterable.  
There may be a case when a field is to be sortable but not filterable.

The ability to define sortable fields, independently of the filterable columns.

### What benefits will this change bring?

Allow defining of sortable fields, independently of the filterable columns. 

### Additional context

Maybe either a seperate function to set sortable, with optional marking as default.

**Comment by Gman98ish** [comment]
I'll have a think about this one @rslsystems 

Let us know if you come up with a good interface for it
